# Generated by Django 3.2.3 on 2021-05-30 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('driverAPI', '0001_initial'),
        ('passengerAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverrideshistory',
            name='passenger_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passengerAPI.passenger'),
        ),
        migrations.AddField(
            model_name='driverlocation',
            name='driver_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driverAPI.driver'),
        ),
    ]
